---
- hosts: localhost
  gather_facts: False
  module_defaults:
    kubernetes.core.k8s:
      namespace: default

  tasks:
    - name: Deployment (FastAPI)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: fastapi
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: fastapi
            template:
              metadata:
                labels:
                  app: fastapi
              spec:
                containers:
                - name: fastapi
                  image: fastapi-app
                  imagePullPolicy: Never
                  ports:
                  - containerPort: 8000

    - name: Service (FastAPI)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: fastapi
          spec:
            selector:
              app: fastapi
            ports:
            - port: 8000
              targetPort: 8000
            type: LoadBalancer

    - name: Deployment (Redis)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: redis
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: redis
            template:
              metadata:
                labels:
                  app: redis
              spec:
                containers:
                - name: redis
                  image: redis:7.0-alpine
                  ports:
                  - containerPort: 6379

    - name: Service (Redis)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: redis
          spec:
            selector:
              app: redis
            ports:
            - port: 6379
            type: ClusterIP
