---
- hosts: localhost
  gather_facts: False
  module_defaults:
    kubernetes.core.k8s:
      namespace: default

  tasks:
    - name: Deployment (FastAPI)
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: Deployment
        name: fastapi

    - name: Service (FastAPI)
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        name: fastapi

    - name: Deployment (Redis)
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: Deployment
        name: redis

    - name: Service (Redis)
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        name: redis
