apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- fastapi-deployment.yaml
- fastapi-service.yaml
- redis-deployment.yaml
- redis-service.yaml

buildMetadata: [managedByLabel]
