apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

replicas:
- name: fastapi
  count: 1

patches:
  - target:
      kind: Service
      name: fastapi
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP

commonLabels:
  env: dev

buildMetadata: [managedByLabel]
